#!/usr/bin/env python3
"""SPEC17rev2 Step 7 — cross-fit TS generation.

Usage:
    python 07_generate_crossfit.py --fold K

For fold K: load ckpt/fold{K}/last.ckpt (or the newest .ckpt if last missing),
generate TS for every reaction in fold K, write to generated/crossfit/rxn_NNNN.xyz.

Cross-fit invariant (SPEC §0.3): rxn i must be generated by the model whose
train set EXCLUDED i. This is enforced by:
  1. Reading folds.csv up front
  2. Only iterating over rxn_id where fold == K
  3. Writing manifest.csv row per generation with generating_model=K
  4. main() asserts folds.csv[rxn_id] == generating_model

Idempotent: rxn already emitted with matching generating_model is skipped.

React-OT inference API is imported lazily. Since react-ot ships evaluation.py
targeted at Transition1x, we bypass it and call the model directly via the
LitDDPMModule / LitSBModule loaded from checkpoint. If the class name in the
ckpt hyper_parameters is unrecognized, the script fails loud with instructions.
"""
from __future__ import annotations

import argparse
import csv
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path("/gpfs/home1/yeseo1ee/projects/eda-asm-prediction")
BASE = REPO / "analysis/otfm_train"
ROT = REPO / "external/react-ot"
GEN = BASE / "generated" / "crossfit"
MANIFEST = GEN.parent / "manifest.csv"
N_FOLDS = 5

for _d in ("artifacts", "data", "ckpt", "generated", "logs", "figures"):
    (BASE / _d).mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(BASE))
from _rot_patches import apply_all as apply_rot_patches  # noqa: E402

# React-OT sampler knobs — SPEC §17 quote: nfe=25 / solver ode.
SAMPLER_NFE = int(os.environ.get("SAMPLER_NFE", "25"))
SAMPLER_MAX_NUM = int(os.environ.get("SAMPLER_MAX_NUM", "1600"))

Z_TO_SYMBOL = {1: "H", 6: "C", 7: "N", 8: "O", 9: "F",
               15: "P", 16: "S", 17: "Cl", 35: "Br", 53: "I"}


def write_xyz(path: Path, syms: list[str], xyz: np.ndarray, comment: str = "") -> None:
    tmp = path.with_suffix(".xyz.tmp")
    n = len(syms)
    with open(tmp, "w") as f:
        f.write(f"{n}\n{comment}\n")
        for s, (x, y, z) in zip(syms, xyz):
            f.write(f"{s} {x:.6f} {y:.6f} {z:.6f}\n")
    tmp.replace(path)


def find_checkpoint(fold_dir: Path) -> Path:
    for name in ("last.ckpt", "best.ckpt"):
        p = fold_dir / name
        if p.exists():
            return p
    hits = sorted(fold_dir.rglob("*.ckpt"), key=lambda x: x.stat().st_mtime)
    if hits:
        return hits[-1]
    raise FileNotFoundError(f"no .ckpt under {fold_dir}")


def load_model(ckpt_path: Path):
    """Load the trained model. Tries LitDDPMModule then LitSBModule."""
    sys.path.insert(0, str(ROT))
    import torch  # noqa: F401

    last_err = None
    for mod_name, cls_name in (
        ("reactot.trainer.pl_trainer", "DDPMModule"),
        ("reactot.trainer.pl_trainer", "SBModule"),
        ("reactot.trainer.pl_trainer_ts1x", "DDPMModule"),
    ):
        try:
            mod = __import__(mod_name, fromlist=[cls_name])
            cls = getattr(mod, cls_name)
            m = cls.load_from_checkpoint(str(ckpt_path), map_location="cpu")
            print(f"loaded {cls_name} from {ckpt_path}")
            return m
        except Exception as e:  # noqa: BLE001
            last_err = e
            continue
    raise RuntimeError(
        f"could not load checkpoint {ckpt_path}. Verify react-ot module layout "
        f"and update load_model() imports. Last error: {last_err}"
    )


def load_fold_test(fold: int):
    """Prefer per-fold test pkl written by Step 6; fall back to slicing coley_all.pkl."""
    p = BASE / "ckpt" / f"fold{fold}" / "data" / f"test_fold{fold}.pkl"
    if p.exists():
        with open(p, "rb") as f:
            return pickle.load(f)
    print(f"[WARN] {p} missing; reconstructing from coley_all.pkl + folds.csv")
    with open(BASE / "data" / "coley_all.pkl", "rb") as f:
        data = pickle.load(f)
    folds = pd.read_csv(BASE / "artifacts" / "folds.csv").set_index("rxn_id")
    test_ids = set(folds[folds.fold == fold].index)
    keep = [i for i, r in enumerate(data["rxn_id"]) if r in test_ids]
    return {
        "reactant": {k: [data["reactant"][k][i] for i in keep]
                     for k in data["reactant"]},
        "transition_state": {k: [data["transition_state"][k][i] for i in keep]
                             for k in data["transition_state"]},
        "product": {k: [data["product"][k][i] for i in keep]
                    for k in data["product"]},
        "single_fragment": [data["single_fragment"][i] for i in keep],
        "rxn_id": [data["rxn_id"][i] for i in keep],
    }


def already_generated(rid: int, fold: int) -> bool:
    xyz = GEN / f"rxn_{rid:04d}.xyz"
    if not xyz.exists() or not MANIFEST.exists():
        return False
    with open(MANIFEST) as f:
        rd = csv.DictReader(f)
        for row in rd:
            if int(row["rxn_id"]) == rid:
                return int(row["generating_model"]) == fold
    return False


def append_manifest(rows: list[dict]) -> None:
    header = ["rxn_id", "generating_model", "n_atoms", "path"]
    write_header = not MANIFEST.exists()
    with open(MANIFEST, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=header)
        if write_header:
            w.writeheader()
        for r in rows:
            w.writerow(r)


def generate_one(model, rxn: dict, device: str = "cuda"):
    """Call the model's OT sampler to produce a TS structure.

    react-ot's sampling entry point varies across releases; this helper tries
    `sample`, `generate_ts`, `predict_ts` in order and raises if none work.
    """
    import torch

    charges = torch.tensor(rxn["charges"], dtype=torch.long)
    r_pos = torch.tensor(rxn["R"], dtype=torch.float32)
    p_pos = torch.tensor(rxn["P"], dtype=torch.float32)
    for method_name in ("sample_rp_to_ts", "sample", "generate_ts", "predict_ts"):
        method = getattr(model, method_name, None)
        if method is None:
            continue
        try:
            with torch.no_grad():
                out = method(
                    reactant_positions=r_pos.to(device),
                    product_positions=p_pos.to(device),
                    charges=charges.to(device),
                    nfe=SAMPLER_NFE,
                    solver="ode",
                )
            arr = out.detach().cpu().numpy() if hasattr(out, "detach") else np.asarray(out)
            return arr
        except TypeError:
            continue
        except Exception as e:  # noqa: BLE001
            raise RuntimeError(
                f"model.{method_name} raised {type(e).__name__}: {e}. "
                "Update generate_one() to match your react-ot API."
            ) from e
    raise RuntimeError(
        "no sampling method found on model. Update generate_one() to match "
        "your react-ot inference API (see reactot/evaluation.py for hints)."
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fold", type=int, required=True, choices=range(N_FOLDS))
    args = ap.parse_args()
    fold = args.fold

    GEN.mkdir(parents=True, exist_ok=True)
    fold_dir = BASE / "ckpt" / f"fold{fold}"
    ckpt = find_checkpoint(fold_dir)
    # GATE-6b: ensure react-ot's dataset module sees the 7-element mapping.
    # ckpt.load_from_checkpoint triggers dataset imports on some releases.
    apply_rot_patches(ROT)
    model = load_model(ckpt)

    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device).eval()

    ds = load_fold_test(fold)
    folds = pd.read_csv(BASE / "artifacts" / "folds.csv").set_index("rxn_id")

    new_rows = []
    n_skip = 0
    for i, rid in enumerate(ds["rxn_id"]):
        # cross-fit safety
        if folds.at[rid, "fold"] != fold:
            print(f"[FATAL] rxn {rid} not in fold {fold}", file=sys.stderr)
            return 1
        if already_generated(rid, fold):
            n_skip += 1
            continue
        rxn = {
            "charges": ds["reactant"]["charges"][i],
            "R": ds["reactant"]["positions"][i],
            "P": ds["product"]["positions"][i],
        }
        ts_xyz = generate_one(model, rxn, device=device)
        syms = [Z_TO_SYMBOL[z] for z in rxn["charges"]]
        out = GEN / f"rxn_{rid:04d}.xyz"
        write_xyz(out, syms, ts_xyz,
                  comment=f"rid={rid} fold={fold} nfe={SAMPLER_NFE}")
        new_rows.append(dict(rxn_id=rid, generating_model=fold,
                              n_atoms=len(syms), path=str(out)))
        if (i + 1) % 100 == 0:
            print(f"  fold {fold}: {i+1}/{len(ds['rxn_id'])} generated")
    if new_rows:
        append_manifest(new_rows)

    print(f"fold {fold}: generated {len(new_rows)}   skipped {n_skip}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
