#!/usr/bin/env python3
"""SPEC17rev2 Step 7 — cross-fit TS generation.

Usage:
    python 07_generate_crossfit.py --fold K

For fold K: load ckpt/fold{K}/last.ckpt (or the newest .ckpt if last missing),
generate TS for every reaction in fold K, write to generated/crossfit/rxn_NNNN.xyz.

Cross-fit invariant (SPEC §0.3): rxn i must be generated by the model whose
train set EXCLUDED i. This is enforced by:
  1. Reading folds.csv up front
  2. Only iterating over rxn_id where fold == K
  3. Writing manifest.csv row per generation with generating_model=K
  4. main() asserts folds.csv[rxn_id] == generating_model

Idempotent: rxn already emitted with matching generating_model is skipped.

React-OT inference API is imported lazily. Since react-ot ships evaluation.py
targeted at Transition1x, we bypass it and call the model directly via the
LitDDPMModule / LitSBModule loaded from checkpoint. If the class name in the
ckpt hyper_parameters is unrecognized, the script fails loud with instructions.
"""
from __future__ import annotations

import argparse
import csv
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path("/gpfs/home1/yeseo1ee/projects/eda-asm-prediction")
BASE = REPO / "analysis/otfm_train"
ROT = REPO / "external/react-ot"
GEN = BASE / "generated" / "crossfit"
MANIFEST = GEN.parent / "manifest.csv"
N_FOLDS = 5

for _d in ("artifacts", "data", "ckpt", "generated", "logs", "figures"):
    (BASE / _d).mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(BASE))
from _rot_patches import apply_all as apply_rot_patches  # noqa: E402

# React-OT sampler knobs — SPEC §17 quote: nfe=25 / solver ode.
SAMPLER_NFE = int(os.environ.get("SAMPLER_NFE", "25"))
SAMPLER_MAX_NUM = int(os.environ.get("SAMPLER_MAX_NUM", "1600"))

Z_TO_SYMBOL = {1: "H", 6: "C", 7: "N", 8: "O", 9: "F",
               15: "P", 16: "S", 17: "Cl", 35: "Br", 53: "I"}


def write_xyz(path: Path, syms: list[str], xyz: np.ndarray, comment: str = "") -> None:
    tmp = path.with_suffix(".xyz.tmp")
    n = len(syms)
    with open(tmp, "w") as f:
        f.write(f"{n}\n{comment}\n")
        for s, (x, y, z) in zip(syms, xyz):
            f.write(f"{s} {x:.6f} {y:.6f} {z:.6f}\n")
    tmp.replace(path)


def find_checkpoint(fold_dir: Path) -> Path:
    for name in ("last.ckpt", "best.ckpt"):
        p = fold_dir / name
        if p.exists():
            return p
    hits = sorted(fold_dir.rglob("*.ckpt"), key=lambda x: x.stat().st_mtime)
    if hits:
        return hits[-1]
    raise FileNotFoundError(f"no .ckpt under {fold_dir}")


def load_model(ckpt_path: Path):
    """Load the trained model. Tries several react-ot module layouts."""
    import traceback
    sys.path.insert(0, str(ROT))
    import torch  # noqa: F401

    errors = []
    for mod_name, cls_name in (
        ("reactot.trainer.pl_trainer", "SBModule"),
        ("reactot.trainer.pl_trainer", "DDPMModule"),
        ("reactot.trainer.pl_trainer_ts1x", "DDPMModule"),
    ):
        try:
            mod = __import__(mod_name, fromlist=[cls_name])
            cls = getattr(mod, cls_name)
            m = cls.load_from_checkpoint(str(ckpt_path), map_location="cpu")
            print(f"loaded {cls_name} from {ckpt_path}")
            return m
        except Exception as e:  # noqa: BLE001
            errors.append((mod_name, cls_name, e, traceback.format_exc()))
            continue
    # Print all attempts' tracebacks so the user can diagnose which of the
    # three failure modes actually blocked loading.
    for mod_name, cls_name, e, tb in errors:
        print(f"\n=== attempt: {mod_name}.{cls_name} ===")
        print(tb, flush=True)
    raise RuntimeError(
        f"could not load checkpoint {ckpt_path}. Verify react-ot module "
        f"layout and update load_model() imports. See tracebacks above."
    )


def load_fold_test(fold: int):
    """Prefer per-fold test pkl written by Step 6; fall back to slicing coley_all.pkl."""
    p = BASE / "ckpt" / f"fold{fold}" / "data" / f"test_fold{fold}.pkl"
    if p.exists():
        with open(p, "rb") as f:
            return pickle.load(f)
    print(f"[WARN] {p} missing; reconstructing from coley_all.pkl + folds.csv")
    with open(BASE / "data" / "coley_all.pkl", "rb") as f:
        data = pickle.load(f)
    folds = pd.read_csv(BASE / "artifacts" / "folds.csv").set_index("rxn_id")
    test_ids = set(folds[folds.fold == fold].index)
    keep = [i for i, r in enumerate(data["rxn_id"]) if r in test_ids]
    return {
        "reactant": {k: [data["reactant"][k][i] for i in keep]
                     for k in data["reactant"]},
        "transition_state": {k: [data["transition_state"][k][i] for i in keep]
                             for k in data["transition_state"]},
        "product": {k: [data["product"][k][i] for i in keep]
                    for k in data["product"]},
        "single_fragment": [data["single_fragment"][i] for i in keep],
        "rxn_id": [data["rxn_id"][i] for i in keep],
    }


def already_generated(rid: int, fold: int) -> bool:
    xyz = GEN / f"rxn_{rid:04d}.xyz"
    if not xyz.exists() or not MANIFEST.exists():
        return False
    with open(MANIFEST) as f:
        rd = csv.DictReader(f)
        for row in rd:
            if int(row["rxn_id"]) == rid:
                return int(row["generating_model"]) == fold
    return False


def append_manifest(rows: list[dict]) -> None:
    header = ["rxn_id", "generating_model", "n_atoms", "path"]
    write_header = not MANIFEST.exists()
    with open(MANIFEST, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=header)
        if write_header:
            w.writeheader()
        for r in rows:
            w.writerow(r)


def main() -> int:
    """Run the fold's SBModule over its test set via `eval_sample_batch`.

    Real react-ot inference API (from reactot/trainer/test_integrator.ipynb):
      1. model.setup(stage="test")  → loads test.pkl from training_config.datadir
      2. model.test_dataloader()    → yields (representations, conditions) tuples
      3. model.eval_sample_batch(batch, return_all=True)
           → (r_pos, x0_pred, p_pos, x0_size, x0_other, rmsds)
         x0_pred is the generated TS positions (concatenated across the batch);
         x0_size gives the per-rxn atom count so we can split.

    The test.pkl symlink (→ test_fold{K}.pkl) is created by Step 6 alongside
    train_rpsb_all.pkl / valid_rpsb_all.pkl, so the setup() call sees the
    fold's held-out reactions under react-ot's expected filename.
    """
    ap = argparse.ArgumentParser()
    ap.add_argument("--fold", type=int, required=True, choices=range(N_FOLDS))
    args = ap.parse_args()
    fold = args.fold

    GEN.mkdir(parents=True, exist_ok=True)
    fold_dir = BASE / "ckpt" / f"fold{fold}"
    ckpt = find_checkpoint(fold_dir)
    apply_rot_patches(ROT)
    model = load_model(ckpt)

    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # Point the model at THIS fold's data (in case ckpt was resumed from a
    # different fold's config).
    fold_data = str(fold_dir / "data") + "/"
    model.training_config["datadir"] = fold_data
    model.training_config["use_sampler"] = False   # deterministic batching
    model.training_config["swapping_react_prod"] = False
    model.setup(stage="test", device=device, swapping_react_prod=False)
    model = model.to(device).eval()
    model.nfe = SAMPLER_NFE

    # react-ot's `EnSB.sample()` references `self.opt.solver` etc. The OPT
    # object is defined in train_rpsb_ts1x.py and manually attached to the
    # trainer (train script line 211: `ddpm.ddpm.opt = opt`). Reproduce
    # here so inference works with the same convention. We pick solver="ode"
    # (matches SPEC17rev2 §7 which specifies ODE integration for OT).
    class _OPT:
        def __init__(self):
            self.solver = "ode"
            self.method = "euler"
            self.atol = 1e-2
            self.rtol = 1e-2
    model.ddpm.opt = _OPT()
    # eval_sample_batch reads model.ot_ode (used at sample-time flag)
    if not hasattr(model, "ot_ode"):
        model.ot_ode = True

    # Load fold test pkl to recover rxn_id order (SBModule strips it from batch).
    ds = load_fold_test(fold)
    folds = pd.read_csv(BASE / "artifacts" / "folds.csv").set_index("rxn_id")
    test_rids = list(ds["rxn_id"])
    for rid in test_rids:
        if folds.at[rid, "fold"] != fold:
            print(f"[FATAL] rxn {rid} not in fold {fold}", file=sys.stderr)
            return 1

    # Iterate test dataloader in bz=8 batches; ORDER must match test.pkl since
    # ProcessedTS1x reads it linearly and DataLoader shuffle=False.
    bz_test = int(os.environ.get("BATCH_SIZE_TEST", "8"))
    from torch.utils.data import DataLoader
    loader = DataLoader(
        model.test_dataset,
        batch_size=bz_test,
        shuffle=False,
        num_workers=0,
        collate_fn=model.test_dataset.collate_fn,
    )

    new_rows = []
    n_skip = 0
    cursor = 0
    for batch_idx, batch in enumerate(loader):
        # Fast-skip if EVERY rxn in this batch is already generated.
        this_batch_rids = test_rids[cursor:cursor + bz_test]
        if all(already_generated(rid, fold) for rid in this_batch_rids):
            n_skip += len(this_batch_rids)
            cursor += len(this_batch_rids)
            continue
        # Sample.
        try:
            batch = tuple(
                [
                    {k: (v.to(device) if hasattr(v, "to") else v)
                     for k, v in rep.items()}
                    for rep in batch[0]
                ],
                batch[1],
            ) if False else batch  # keep dataloader default collate output as-is
        except Exception:
            pass
        r_pos, x0_pred, p_pos, x0_size, x0_other, rmsds = model.eval_sample_batch(
            batch, return_all=True,
        )
        # Split concatenated positions per rxn using x0_size.
        pos_np = x0_pred.detach().cpu().numpy()
        sizes = [int(s) for s in x0_size]
        assert sum(sizes) == pos_np.shape[0], (
            f"size mismatch: sizes={sizes} pos_len={pos_np.shape[0]}"
        )
        offset = 0
        for k, n in enumerate(sizes):
            if k >= len(this_batch_rids):
                break
            rid = this_batch_rids[k]
            if already_generated(rid, fold):
                offset += n
                continue
            rxn_pos = pos_np[offset:offset + n]
            offset += n
            # syms: reconstruct from ds charges (test.pkl order = loader order)
            chg = ds["reactant"]["charges"][cursor + k]
            syms = [Z_TO_SYMBOL[z] for z in chg]
            if len(syms) != n:
                print(f"[WARN] rid {rid}: syms={len(syms)} vs x0_size={n}",
                      file=sys.stderr)
                continue
            out = GEN / f"rxn_{rid:04d}.xyz"
            write_xyz(out, syms, rxn_pos,
                      comment=f"rid={rid} fold={fold} nfe={SAMPLER_NFE}")
            new_rows.append(dict(rxn_id=rid, generating_model=fold,
                                  n_atoms=n, path=str(out)))
        cursor += len(this_batch_rids)
        if (batch_idx + 1) % 20 == 0:
            print(f"  fold {fold}: batch {batch_idx+1}, cursor {cursor}/{len(test_rids)}",
                  flush=True)

    if new_rows:
        append_manifest(new_rows)
    print(f"fold {fold}: generated {len(new_rows)}   skipped {n_skip}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
