gs_path: /gpfs/home1/yeseo1ee/projects/eda-asm-prediction/paper_reproduction_203/pipeline_work/tt_gs.pkl
ts_path: /gpfs/home1/yeseo1ee/projects/eda-asm-prediction/paper_reproduction_203/pipeline_work/tt_ts.pkl
dist_gs_path: /gpfs/home1/yeseo1ee/projects/eda-asm-prediction/paper_reproduction_203/pipeline_work/tt_dist_gs.pkl
am1_barriers_path: /gpfs/home1/yeseo1ee/projects/eda-asm-prediction/paper_reproduction_203/barriers/am1_barriers_gated.pkl
dft_barriers_path: /gpfs/home1/yeseo1ee/projects/eda-asm-prediction/paper_reproduction_203/barriers/dft_barriers_gated.pkl
filename: tt_features_gated.pkl
