#!/bin/bash
# SLURM-array retry of recoverable ADF failures.
#
# Reads:   outputs/asr_v1/retry/recoverable_dirs.txt  (one absolute path per line)
# Targets: SLURM compute partitions cpu1/cpu2.
#
# Why multi-reaction-per-task:
#   Our SLURM account has MaxSubmit=20 and MaxJobs=10 per user. A 160-element
#   array would exceed MaxSubmit at submission time. Instead we run a
#   10-element array where each task sequentially processes ~16 reactions.
#   This keeps us at 10/10 running and 10/20 submitted, leaving headroom.
#
# Why we shell out to each reaction's own run_reaction.sh:
#   Each per-reaction run_reaction.sh has all the fragment metadata
#   (atoms-a, atoms-b, charges, multiplicities, fragment method, dataset
#   Ea reference) hard-baked into the write_status.py call — generated by
#   build_adf_inputs.py at deck-creation time. Calling that script directly
#   means we don't need to reconstruct any of that metadata in this wrapper.
#
# License: 2026-06-02 license (Linux* hostid pattern) covers all .hpc
# compute nodes. Verified on n040.hpc 2026-06-02 21:00 KST.

#SBATCH --job-name=asr_v1_adf_retry
#SBATCH --array=0-9
#SBATCH --partition=cpu1,cpu2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time=24:00:00
#SBATCH --output=outputs/asr_v1/logs/retry-%A_%a.out
#SBATCH --error=outputs/asr_v1/logs/retry-%A_%a.err

set -o pipefail
REPO=/gpfs/home1/yeseo1ee/projects/eda-asm-prediction
LIST="$REPO/outputs/asr_v1/retry/recoverable_dirs.txt"
REACTIONS_PER_TASK=${REACTIONS_PER_TASK:-16}

mkdir -p "$REPO/outputs/asr_v1/logs"
mapfile -t DIRS < "$LIST"
N_TOTAL=${#DIRS[@]}

START_IDX=$(( SLURM_ARRAY_TASK_ID * REACTIONS_PER_TASK ))
END_IDX=$(( START_IDX + REACTIONS_PER_TASK - 1 ))
if [ "$END_IDX" -ge "$N_TOTAL" ]; then
    END_IDX=$(( N_TOTAL - 1 ))
fi
if [ "$START_IDX" -ge "$N_TOTAL" ]; then
    echo "[skip] task $SLURM_ARRAY_TASK_ID has no work ($START_IDX >= $N_TOTAL)"
    exit 0
fi

echo "============================================================"
echo "=== array task $SLURM_ARRAY_TASK_ID :"
echo "===   processing reactions [$START_IDX..$END_IDX] of $N_TOTAL"
echo "===   host=$(hostname)  cpus=$SLURM_CPUS_PER_TASK  mem=$SLURM_MEM_PER_NODE"
echo "============================================================"

# ----- AMS env -----
source /home1/yeseo1ee/ams2026.103/amsbashrc.sh
if [ -z "${SCMLICENSE:-}" ]; then
    echo "[fatal] SCMLICENSE unset after sourcing amsbashrc.sh"
    exit 3
fi
# ----- end AMS env -----

# NSCM=1 inside each AMS call — matches the gate1 xargs-P4 baseline.
# Why: run_reaction.sh backgrounds c4 + c5 (-> 2 srun steps) then runs
# c1/c2 sequentially (each is a srun step). With NSCM>1, each step would
# also request NSCM cores, and the SLURM job's cpus-per-task cap rejects
# the overlapping steps ("More processors requested than permitted").
# At NSCM=1, peak concurrent cores = 3 (c1 + c4 + c5), fits cpus-per-task=4.
# Wall per reaction matches gate1 historical mean (~69 min).
# run_reaction.sh reads NSCM via `${SLURM_NTASKS:-1}` — SLURM_NTASKS is
# already 1 in this allocation (--ntasks=1), so leave it untouched.
ulimit -s unlimited 2>/dev/null || true

is_already_ok() {
    # An entry counts as "already OK" only when:
    #   (1) status.json exists and exit_code == 0
    #   (2) all calc_status values are converged or n/a_single_atom
    #   (3) every .out file referenced in output_files actually exists on disk
    # Condition (3) catches the May-29 PBE0 relics whose status.json says
    # "converged" but whose .out files were wiped during the disk crisis.
    local status_json="$1"
    [ -f "$status_json" ] || return 1
    python3 - "$status_json" <<'PY' 2>/dev/null
import json, os, sys
status_p = sys.argv[1]
s = json.load(open(status_p))
rxn_dir = os.path.dirname(status_p)
ok_states = all(
    v in ("converged", "n/a_single_atom")
    for v in s.get("calc_status", {}).values()
)
ok_exit = s.get("exit_code") == 0
ok_files = all(
    os.path.isfile(os.path.join(rxn_dir, fname))
    for fname in s.get("output_files", {}).values()
)
sys.exit(0 if (ok_exit and ok_states and ok_files) else 1)
PY
}

process_one() {
    local RXN_DIR="$1"
    local RID
    RID="$(basename "$RXN_DIR")"

    if is_already_ok "$RXN_DIR/status.json"; then
        echo "[skip] $RID — status.json already shows converged"
        return 0
    fi
    if [ ! -f "$RXN_DIR/run_reaction.sh" ]; then
        echo "[err]  $RID — no run_reaction.sh in $RXN_DIR"
        return 1
    fi

    echo
    echo "--- $(date -Iseconds) START $RID  (cwd→$RXN_DIR)"
    pushd "$RXN_DIR" >/dev/null
    bash run_reaction.sh
    local RC=$?
    popd >/dev/null
    echo "--- $(date -Iseconds) END   $RID  rc=$RC"
    return $RC
}

N_OK=0; N_SKIP=0; N_FAIL=0
for IDX in $(seq "$START_IDX" "$END_IDX"); do
    RXN_DIR="${DIRS[$IDX]}"
    process_one "$RXN_DIR"
    case $? in
        0) if is_already_ok "$RXN_DIR/status.json"; then N_OK=$((N_OK+1)); else N_SKIP=$((N_SKIP+1)); fi ;;
        *) N_FAIL=$((N_FAIL+1)) ;;
    esac
done

echo
echo "============================================================"
echo "=== array task $SLURM_ARRAY_TASK_ID COMPLETE"
echo "===   ok = $N_OK,  skip/notok = $N_SKIP,  fail = $N_FAIL"
echo "============================================================"
exit 0
